# Clean and don't fail
install:
  - rm -rf docs/* || exit 0
  - chmod 777 ./bin/hugo

# Build the website
script:
  - ./bin/hugo -d docs

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master